### ISSUE TITLE
I have infinite error 

### ISSUE THREAD

**Issue by Hellomik2002** [ignatz/vector_tile_it#1]
<img width="1260" alt="Screenshot 2024-05-17 at 10 16 19 AM" src="https://github.com/ignatz/vector_tile_it/assets/30003495/cc1b9873-2c94-4928-aeab-7986cc072d24">
<img width="711" alt="Screenshot 2024-05-17 at 10 16 38 AM" src="https://github.com/ignatz/vector_tile_it/assets/30003495/a2dee31c-3ba1-49d4-8dbd-3a32cda99c31">

**Comment by ignatz** [comment]
I'm not sure what you mean by "infinite error". What you're experiencing is the style parser falling over a maptiler style configuration. I did spend a little time trying to iron it out. The style file parses now but the renderer still gets thrown off by something that needs further investigation.

If you'd just like to try out this lib, use mapbox for now.

**Comment by ignatz** [comment]
https://github.com/ignatz/vector_tile_it/commit/ba14146912c7a00ed3cb3d2b0cc042d24ab631ab fixes the use of MapTiler sources.
